CREATE TABLE staging_users (
    id bigint PRIMARY KEY,
    entity_type character varying(256),
    label character varying(256),
    icon character varying(256),
    first_name character varying(256),
    last_name character varying(256),
    email character varying(256),
    created_by character varying(256),
    updated_by character varying(256),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    departments jsonb,
    priority_departments jsonb,
    restricted_departments jsonb,
    telephone character varying(256),
    contact character varying(256),
    roles jsonb,
    user_groups jsonb,
    country character varying(256),
    job_title character varying(256),
    legacy_email character varying(256),
    supervisor_groups jsonb,
    user_type character varying(256),
    webrtc_device character varying(256),
    permission_messaging BOOLEAN,
    permission_report BOOLEAN,
    permission_settings BOOLEAN,
    permission_supervisor BOOLEAN,
    auto_voice_answer_timeout bigint,
    channel_priority jsonb,
    channel_restriction jsonb,
    default_currency jsonb,
    primary_device character varying(256),
    disable_auto_logout BOOLEAN,
    divert_destination character varying(256),
    voice_queue_timeout bigint,
    enabled BOOLEAN,
    enforce_outbound_endpoint BOOLEAN,
    extension character varying(256),
    followed_by jsonb,
    inbound_transfer_department jsonb,
    force_turn BOOLEAN,
    force_turn_tcp BOOLEAN,
    outbound_endpoint jsonb,
    ice_timeout bigint,
    idle_auto_recovery BOOLEAN,
    idle_auto_recovery_timeout bigint,
    custom_interaction_capacity jsonb,
    linked_entities jsonb,
    locked BOOLEAN,
    voicemail_timeout bigint,
    mobile_device jsonb,
    not_responding_auto_recovery BOOLEAN,
    not_responding_timeout bigint,
    permission_restrict_acd_routing BOOLEAN,
    permission_restrict_acd_to_voice BOOLEAN,
    pbx_user BOOLEAN,
    remote_access BOOLEAN,
    permission_restrict_login BOOLEAN,
    use_custom_interaction_capacity BOOLEAN,
    voicemail_email character varying(256),
    voicemail_enabled BOOLEAN,
    voicemail_message character varying(256),
    whatsapp_notifications_telephone character varying(256),
    __created_by bigint,
    __updated_by bigint,
    __departments jsonb,
    __roles jsonb,
    __webrtc_device bigint,
    __primary_device bigint,
    __priority_departments jsonb,
    __restricted_departments jsonb,
    __user_groups jsonb,
    __supervisor_groups jsonb,
    __followed_by jsonb,
    __linked_entities jsonb,
    __channel_priority jsonb,
    __channel_restriction jsonb,
    __country character varying(256),
    __country__color character varying(256),
    __user_type character varying(256),
    __user_type__color character varying(256),
    user_status jsonb
);